version: "3.9"
services:
  postgres:
    image: postgres:14.5
    container_name: "awesome-pg-db-14.5"
    environment:
      POSTGRES_DB: "awesome"
      POSTGRES_USER: "andrvat"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"