version: "3.9"
services:
  postgres:
    image: postgres:14.5
    container_name: "awesome-pg-db-14.5"
    environment:
      POSTGRES_DB: "awesome"
      POSTGRES_USER: "andrvat"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
  migration:
    image: migrate/migrate
    network_mode: host
    volumes:
      - /mnt/331d7bdc-0b63-46e7-9097-91b34740536d/GolandProjects/awesomeProject/migrations:/migrations
    command: '-path /migrations -database postgres://andrvat:1234@localhost:5432/awesome?sslmode=disable up'
    depends_on:
      - postgres



