bind_addr = ":5544"
log_level = "Info"
database_url = "host=localhost port=5432 user=andrvat password=1234 dbname=awesome sslmode=disable"
database_driver_name = "postgres"
session_key = "774F1D42AE59A12CC3A2A936C3518"